// Quotes for the SalonID Design form
// Add your 200 quotes to this array. Each quote will appear and disappear above the footer.

export const quotes: readonly string[] = [
  `Beauty begins the moment you decide to be yourself." - Coco Chanel`,
  `The best color in the whole world is the one that looks good on you." - Coco Chanel`,
  `Creativity is intelligence having fun." - Albert Einstein`,
  `The secret to beauty is simple: be who you are." - Bobbi Brown`,
  `Elegance is the only beauty that never fades." - Audrey Hepburn`,
  `The future belongs to those who believe in the beauty of their dreams." - Eleanor Roosevelt`,
  `Design is not just what it looks like and feels like. Design is how it works." - Steve Jobs`,
  `Quality is the best business plan." - John Lasseter`,
  `Your brand is what other people say about you when you're not in the room." - Jeff Bezos`,
  `Simplicity is the ultimate sophistication." - Leonardo da Vinci`,
  `Style is a way to say who you are without having to speak." - Rachel Zoe`,
  `To be creative means to be in love with life." - Osho`,
  `Nature gives you the face you have at twenty; it is up to you to merit the face you have at fifty." - Coco Chanel`,
  `A thing of beauty is a joy for ever." - John Keats`,
  `The way to get started is to quit talking and begin doing." - Walt Disney`,
  `Beauty is power; a smile is its sword." - John Ray`,
  `Pour yourself a drink, put on some lipstick, and pull yourself together." - Elizabeth Taylor`,
  `Creativity takes courage." - Henri Matisse`,
  `In order to be irreplaceable one must always be different." - Coco Chanel`,
  `The best-kept secret in the beauty industry is that we're all beautiful.`,
  `Make it simple, but significant." - Don Draper`,
  `Success is not final, failure is not fatal: it is the courage to continue that counts." - Winston Churchill`,
  `Everything has beauty, but not everyone sees it." - Confucius`,
  `Confidence is the best accessory.`,
  `Art is not what you see, but what you make others see." - Edgar Degas`,
  `The details are not the details. They make the design." - Charles Eames`,
  `Do one thing every day that scares you." - Eleanor Roosevelt`,
  `Passion is the genesis of genius." - Tony Robbins`,
  `The artist is nothing without the gift, but the gift is nothing without work." - Émile Zola`,
  `Beauty is the illumination of your soul." - John O'Donohue`,
  `A brand for a company is like a reputation for a person. You earn reputation by trying to do hard things well." - Jeff Bezos`,
  `Invest in your skin. It is going to represent you for a very long time." - Linden Tyler`,
  `The only way to do great work is to love what you do." - Steve Jobs`,
  `Fashions fade, style is eternal." - Yves Saint Laurent`,
  `Let the beauty of what you love be what you do." - Rumi`,
  `Quality means doing it right when no one is looking." - Henry Ford`,
  `There is no exquisite beauty without some strangeness in the proportion." - Edgar Allan Poe`,
  `The most courageous act is still to think for yourself. Aloud." - Coco Chanel`,
  `Your vision will become clear only when you can look into your own heart." - Carl Jung`,
  `Less is more." - Ludwig Mies van der Rohe`,
  `A woman's perfume tells more about her than her handwriting." - Christian Dior`,
  `You can't use up creativity. The more you use, the more you have." - Maya Angelou`,
  `The beautiful is always bizarre." - Charles Baudelaire`,
  `Make your product easier to buy than your competition, or you will find your customers buying from them, not you." - Mark Cuban`,
  `Be faithful to your own taste because nothing you really like is ever out of style." - Billy Baldwin`,
  `Beauty is when you can appreciate yourself." - Zoe Kravitz`,
  `The creative adult is the child who survived." - Ursula K. Le Guin`,
  `Every great dream begins with a dreamer." - Harriet Tubman`,
  `The essence of strategy is choosing what not to do." - Michael Porter`,
  `To live a creative life, we must lose our fear of being wrong." - Joseph Chilton Pearce`,
  `Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring." - Marilyn Monroe`,
  `What you do today can improve all your tomorrows." - Ralph Marston`,
  `There is beauty in simplicity.`,
  `The best cosmetic is a good conscience." - Proverb`,
  `Creativity is contagious, pass it on." - Albert Einstein`,
  `If you don't build your dream, someone else will hire you to help them build theirs." - Dhirubhai Ambani`,
  `The power of a glance has been so much abused in love stories, that it has come to be disbelieved in." - Stendhal`,
  `Happy girls are the prettiest." - Audrey Hepburn`,
  `Your imagination is your preview of life's coming attractions." - Albert Einstein`,
  `Beauty is not in the face; beauty is a light in the heart." - Kahlil Gibran`,
  `Don't be afraid to give up the good to go for the great." - John D. Rockefeller`,
  `The best marketing doesn't feel like marketing." - Tom Fishburne`,
  `To create is to live twice." - Albert Camus`,
  `Glow is the essence of beauty." - Estée Lauder`,
  `The secret of getting ahead is getting started." - Mark Twain`,
  `A brand is a story that is always being told." - Scott Bedbury`,
  `Simplicity is the keynote of all true elegance." - Coco Chanel`,
  `The painter has the Universe in his mind and hands." - Leonardo da Vinci`,
  `Beauty is an attitude." - Estée Lauder`,
  `The function of design is letting design function." - Micha Commeren`,
  `I have no special talent. I am only passionately curious." - Albert Einstein`,
  `Great things in business are never done by one person. They're done by a team of people." - Steve Jobs`,
  `Logic will get you from A to B. Imagination will take you everywhere." - Albert Einstein`,
  `Style is knowing who you are, what you want to say, and not giving a damn." - Orson Welles`,
  `Let your unique awesomeness and positive energy inspire confidence in others.`,
  `The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself." - Mark Caine`,
  `Beauty without expression is boring." - Ralph Waldo Emerson`,
  `Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away." - Antoine de Saint-Exupéry`,
  `The journey of a thousand miles begins with a single step." - Lao Tzu`,
  `The soul that sees beauty may sometimes walk alone." - Johann Wolfgang von Goethe`,
  `It’s not about ideas. It’s about making ideas happen." - Scott Belsky`,
  `Creativity is a wild mind and a disciplined eye." - Dorothy Parker`,
  `Every artist dips his brush in his own soul, and paints his own nature into his pictures." - Henry Ward Beecher`,
  `Outer beauty is a gift. Inner beauty is an accomplishment." - Randi G. Fine`,
  `The purpose of art is washing the dust of daily life off our souls." - Pablo Picasso`,
  `Build something 100 people love, not something 1 million people kind of like." - Brian Chesky`,
  `A flower does not think of competing with the flower next to it. It just blooms." - Zen Shin`,
  `Art enables us to find ourselves and lose ourselves at the same time." - Thomas Merton`,
  `Success is liking yourself, liking what you do, and liking how you do it." - Maya Angelou`,
  `A big business starts small." - Richard Branson`,
  `For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness." - Audrey Hepburn`,
  `The only source of knowledge is experience." - Albert Einstein`,
  `Create your own style… let it be unique for yourself and yet identifiable for others." - Anna Wintour`,
  `Elegance is not about being noticed, it’s about being remembered." - Giorgio Armani`,
  `The desire to create is one of the deepest yearnings of the human soul." - Dieter F. Uchtdorf`,
  `The most important thing is to enjoy your life—to be happy—it's all that matters." - Audrey Hepburn`,
  `Design is the silent ambassador of your brand." - Paul Rand`,
  `Beauty is the opposite of perfection - it's about confidence, charisma and character.`,
  `If you can dream it, you can do it." - Walt Disney`,
  `Authenticity is the new luxury.`,
  `An artist is not paid for his labor but for his vision." - James Whistler`,
  `The human body is the best work of art." - Jess C. Scott`,
  `Your premium brand had better be delivering something special, or it's not going to get the business." - Warren Buffett`,
  `Kindness is a kind of beauty.`,
  `Have no fear of perfection - you'll never reach it." - Salvador Dalí`,
  `Beauty is how you feel inside, and it reflects in your eyes." - Sophia Loren`,
  `What is important in a dress is the woman who is wearing it." - Yves Saint Laurent`,
  `Making money is art and working is art and good business is the best art." - Andy Warhol`,
  `Art should comfort the disturbed and disturb the comfortable." - Cesar A. Cruz`,
  `The best revenge is massive success." - Frank Sinatra`,
  `Personalized beauty is the future.`,
  `The world always seems brighter when you’ve just made something that wasn’t there before." - Neil Gaiman`,
  `Be so good they can't ignore you." - Steve Martin`,
  `I don't design clothes. I design dreams." - Ralph Lauren`,
  `The essence of all beautiful art, all great art, is gratitude." - Friedrich Nietzsche`,
  `A brand is no longer what we tell the consumer it is — it is what consumers tell each other it is." - Scott Cook`,
  `Everything you can imagine is real." - Pablo Picasso`,
  `Character contributes to beauty. It fortifies a woman as her youth fades." - Jacqueline Bisset`,
  `To draw, you must close your eyes and sing." - Pablo Picasso`,
  `People will stare. Make it worth their while." - Harry Winston`,
  `Start where you are. Use what you have. Do what you can." - Arthur Ashe`,
  `Whether you think you can or you think you can't, you're right." - Henry Ford`,
  `The goal of a designer is to listen, observe, understand, sympathize, empathize, synthesize, and glean insights." - Hillman Curtis`,
  `Self-care is not an expense. It's an investment.`,
  `Art is the signature of civilizations." - Jean Cocteau`,
  `Products are made in the factory, but brands are created in the mind." - Walter Landor`,
  `Beauty of style and harmony and grace and good rhythm depend on simplicity." - Plato`,
  `If you are not willing to risk the usual, you will have to settle for the ordinary." - Jim Rohn`,
  `Creativity is not the finding of a thing, but the making something out of it after it is found." - James Russell Lowell`,
  `Simplicity is about subtracting the obvious and adding the meaningful." - John Maeda`,
  `Obsessed is just a word the lazy use to describe the dedicated." - Russell Warren`,
  `What makes you different or weird, that's your strength." - Meryl Streep`,
  `Design creates culture. Culture shapes values. Values determine the future." - Robert L. Peters`,
  `An idea can turn to dust or magic, depending on the talent that rubs against it." - Bill Bernbach`,
  `The true work of art is but a shadow of the divine perfection." - Michelangelo`,
  `Your culture is your brand." - Tony Hsieh`,
  `Beauty should begin in the heart and soul, otherwise cosmetics are useless." - Coco Chanel`,
  `Strive not to be a success, but rather to be of value." - Albert Einstein`,
  `The works must be conceived with fire in the soul but executed with clinical coolness." - Joan Miró`,
  `When you're curious, you find lots of interesting things to do." - Walt Disney`,
  `The best way to predict the future is to create it." - Peter Drucker`,
  `Love of beauty is taste. The creation of beauty is art." - Ralph Waldo Emerson`,
  `There are no rules of architecture for a castle in the clouds." - G.K. Chesterton`,
  `The customer's perception is your reality." - Kate Zabriskie`,
  `I dream my painting, and then I paint my dream." - Vincent van Gogh`,
  `Nature is the best designer.`,
  `It's hard to fail, but it is worse never to have tried to succeed." - Theodore Roosevelt`,
  `The things that make me different are the things that make me." - A.A. Milne`,
  `Art is a line around your thoughts." - Gustav Klimt`,
  `Quality is never an accident. It is always the result of intelligent effort." - John Ruskin`,
  `Focus on the core problem your business solves and put out lots of content and enthusiasm." - Laura Fitton`,
  `I don't do fashion. I am fashion." - Coco Chanel`,
  `Painting is poetry that is seen rather than felt, and poetry is painting that is felt rather than seen." - Leonardo da Vinci`,
  `A problem is a chance for you to do your best." - Duke Ellington`,
  `The beautiful is a manifestation of secret laws of nature." - Johann Wolfgang von Goethe`,
  `You are not a drop in the ocean. You are the entire ocean in a drop." - Rumi`,
  `Art is the most intense mode of individualism that the world has known." - Oscar Wilde`,
  `Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." - Steve Jobs`,
  `Simplicity, carried to an extreme, becomes elegance." - Jon Franklin`,
  `The most beautiful thing you can wear is confidence." - Blake Lively`,
  `Creativity comes from a conflict of ideas." - Donatella Versace`,
  `Every brand isn't for everybody, and that's okay.`,
  `The best artists have no country." - Alfred de Musset`,
  `Beauty is truth, truth beauty." - John Keats`,
  `Genius is one percent inspiration and ninety-nine percent perspiration." - Thomas Edison`,
  `Style is the perfection of a point of view." - Richard Eberhart`,
  `Art is never finished, only abandoned." - Leonardo da Vinci`,
  `If people believe they share values with a company, they will stay loyal to the brand." - Howard Schultz`,
  `Life is a great big canvas, and you should throw all the paint on it you can." - Danny Kaye`,
  `The future of beauty is in your hands.`,
  `What's my favorite thing about my job? The opportunity to create." - Estée Lauder`,
  `A line is a dot that went for a walk." - Paul Klee`,
  `Don't find customers for your products, find products for your customers." - Seth Godin`,
  `Art washes away from the soul the dust of everyday life." - Pablo Picasso`,
  `To be beautiful means to be yourself. You don't need to be accepted by others. You need to accept yourself." - Thich Nhat Hanh`,
  `The chief enemy of creativity is good sense." - Pablo Picasso`,
  `You miss 100% of the shots you don't take." - Wayne Gretzky`,
  `A true masterpiece does not tell everything." - Albert Camus`,
  `Beauty isn't about having a pretty face. It's about having a pretty mind, a pretty heart, and a pretty soul.`,
  `The only thing that I have done that is not creative is my bank account." - H.R. Giger`,
  `Make visible what, without you, might perhaps never have been seen." - Robert Bresson`,
  `I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel." - Maya Angelou`,
  `Elegance is a discipline of life." - Oscar de la Renta`,
  `The role of the artist is to ask questions, not answer them." - Anton Chekhov`,
  `Good design is good business." - Thomas Watson Jr.`,
  `Nothing makes a woman more beautiful than the belief that she is beautiful." - Sophia Loren`,
  `The principles of true art is not to portray, but to evoke." - Jerzy Kosinski`,
  `A successful man is one who can lay a firm foundation with the bricks others have thrown at him." - David Brinkley`,
  `The essence of interior design will always be about people and how they live." - Albert Hadley`,
  `Let's invent tomorrow instead of worrying about what happened yesterday." - Steve Jobs`
];

// Function to get a random quote
export function getRandomQuote(): string {
  return quotes[Math.floor(Math.random() * quotes.length)];
}

// Function to get quotes in sequence
export function getQuoteByIndex(index: number): string {
  return quotes[index % quotes.length];
}

